# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo(self):
    self.driver.get("https://tdd-detroid.onrender.com")
    self.driver.set_window_size(970, 555)
    self.driver.find_element(By.ID, "student-nome").click()
    self.driver.find_element(By.ID, "student-nome").send_keys("douglas")
    self.driver.find_element(By.ID, "student-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".py-p").text == "2024-07-05 01:32:55.301000 INFO Added student. id: 1, Name: douglas"
    self.driver.find_element(By.ID, "course-nome").click()
    self.driver.find_element(By.ID, "course-nome").send_keys("mat")
    self.driver.find_element(By.ID, "course-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(2)").text == "2024-07-05 01:32:55.301000 INFO Added student. id: 1, Name: douglas"
    self.driver.find_element(By.ID, "student-id").click()
    self.driver.find_element(By.ID, "student-id").send_keys("1")
    self.driver.find_element(By.ID, "course-id").click()
    self.driver.find_element(By.ID, "course-id").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #course-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(3)").text == "2024-07-05 01:32:55.301000 INFO Added student. id: 1, Name: douglas"
    self.driver.find_element(By.ID, "discipline-nome").click()
    self.driver.find_element(By.ID, "discipline-nome").send_keys("mat")
    self.driver.find_element(By.ID, "course-discipline-id").click()
    self.driver.find_element(By.ID, "course-discipline-id").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").text == "2024-07-05 01:34:09.151000 FAIL Necessários 3 cursos para se criar a primeira matéria"
    self.driver.find_element(By.ID, "course-nome").click()
    self.driver.find_element(By.ID, "course-nome").click()
    element = self.driver.find_element(By.ID, "course-nome")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "course-nome").send_keys("port")
    self.driver.find_element(By.ID, "course-btn").click()
    self.driver.find_element(By.ID, "course-nome").click()
    self.driver.find_element(By.ID, "course-nome").click()
    element = self.driver.find_element(By.ID, "course-nome")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "course-nome").send_keys("geo")
    self.driver.find_element(By.ID, "course-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").text == "2024-07-05 01:34:39.593000 INFO #Added discipline id: 1, Name: mat, Course: 1"
    self.driver.find_element(By.ID, "discipline-nome").click()
    self.driver.find_element(By.ID, "discipline-nome").click()
    element = self.driver.find_element(By.ID, "discipline-nome")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "discipline-nome").send_keys("mat2")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn").click()
    self.driver.find_element(By.ID, "discipline-nome").click()
    self.driver.find_element(By.ID, "discipline-nome").send_keys("mat3")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn").click()
    self.driver.find_element(By.ID, "subscribe-student-id").click()
    self.driver.find_element(By.ID, "subscribe-student-id").send_keys("1")
    self.driver.find_element(By.ID, "subscribe-discipline-id").click()
    self.driver.find_element(By.ID, "subscribe-discipline-id").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(6) > #course-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").text == "2024-07-05 01:35:14.764000 FAIL Aluno deve se inscrever em 3 materias no minimo"
    self.driver.find_element(By.ID, "subscribe-discipline-id").click()
    self.driver.find_element(By.ID, "subscribe-discipline-id").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(6) > #course-btn").click()
    self.driver.find_element(By.ID, "subscribe-discipline-id").click()
    self.driver.find_element(By.ID, "subscribe-discipline-id").send_keys("3")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(6) > #course-btn").click()
    self.driver.find_element(By.ID, "discipline-nome").click()
    self.driver.find_element(By.ID, "discipline-nome").send_keys("mat4")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn").click()
    self.driver.find_element(By.ID, "subscribe-discipline-id").click()
    self.driver.find_element(By.ID, "subscribe-discipline-id").send_keys("4")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(6) > #course-btn").click()
    self.driver.close()
  
